# -*- coding: utf-8 -*-
"""CD_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fFJ-nOcCmcVzvpC4vqOtM66oKju1NdUU
"""

import re

with open('code.txt', 'r') as file:
  code = file.read()

#code = code.replace('\n', '')
code

# if-elif-else
if re.match(r'\bif\b\s+.*?:\n.*?(?:\belif\b\s+.*?:\n.*?)*?(?:\belse\b:.*?)*?', code): print('yes')
else: print('no')

# switch
if re.findall(r'\bswitch\b\s*\(?.*?\)?\s*\{(?:\s*\bcase\b\s+\w+\s*:\s*.*?)*\s*\bdefault\b\s*:\s*.*?\}', code, re.DOTALL): print('yes')
else: print('no')

for_match = re.search(r'\bfor\s+.+\s+in\s+.+:', content)
while_match = re.search(r'\bwhile\s+.+:', content)
do_match = re.search(r'\bdo\s*\{.*?\}\s*while\s*\(.*?\)\s*;', content, re.DOTALL)