# -*- coding: utf-8 -*-
"""CD_2_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAsi3ZXmlB9-774drO_8jJ9TkRULh-7K
"""

import re

code = ''
with open('demo.txt', 'r') as file:
  code = file.read()
print(code)

declarations = re.findall(r'\b(int|float|double|long|short|char)\b\s+(\w+)\s*(?:=\s*[^;]*)?\s*[;]', code)
declarations

code_upd = re.sub(r'\b(int|float|double|long|short|char)\b\s+(\w+)\s*(?:=\s*[^;]*)?\s*[;]', '', code)
print(code_upd)

vars = [[v, t, False] for v, t in declarations]
vars

for var in vars:
  if re.search(r'\b'+re.escape(var[1])+r'\b', code_upd):
    var[2] = True
vars

